import SEO from '../components/SEO';
export default function TermsOfService() {
  return (
    <>
      
      <SEO title="Terms of Service | ScaleBy" description="Read the terms of service and user agreement for ScaleBy." keywords="terms of service, legal, agreement" />
      <section className="bg-emerald-50 text-slate-800 py-16 lg:py-20 relative overflow-hidden border-b border-emerald-100">
        <div className="absolute inset-0 bg-dot-grid-light opacity-60 pointer-events-none" />
        <div className="absolute -top-32 left-1/2 -translate-x-1/2 h-64 w-[800px] rounded-full bg-emerald-200/40 blur-3xl pointer-events-none" />
        <div className="relative mx-auto max-w-4xl px-4 sm:px-6 lg:px-8 text-center">
          <h1 className="text-3xl sm:text-4xl lg:text-5xl font-extrabold leading-tight text-slate-900">Terms of Service</h1>
          <p className="mt-4 text-emerald-600 text-sm font-semibold tracking-wide uppercase">Last updated: 10 May 2026</p>
        </div>
      </section>

      <section className="py-16 bg-white">
        <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
          <div className="prose prose-slate max-w-none text-slate-700 space-y-8 text-sm leading-relaxed">
            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">1. Introduction</h2>
              <p className="mb-3">
                These Terms and Conditions form a legally binding agreement between ScaleBy Automation LLP, operating under the brand name ScaleBy, and the person, business, merchant, organization, agency, or entity accessing or using our website, application, dashboard, APIs, integrations, support services, or software-as-a-service platform.
              </p>
              <p className="mb-3">
                ScaleBy provides a SaaS platform for business communication, automation, customer engagement, WhatsApp Business API/Cloud API related services, messaging workflows, chatbot automation, CRM, contact management, campaign management, inbox management, integrations, analytics, and related services.
              </p>
              <p>
                By accessing, registering for, subscribing to, integrating with, or using the Platform, you confirm that you have read, understood, and agreed to these Terms, our Privacy Policy, any applicable order form, invoice, subscription plan, product-specific terms, and all policies referenced in these Terms. If you do not agree, you must not use the Platform.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">2. Electronic Record and Legal Validity</h2>
              <p className="mb-3">
                These Terms are an electronic record under the Information Technology Act, 2000 and applicable rules, as amended from time to time. This electronic record is generated by a computer system and does not require any physical or digital signature.
              </p>
              <p>
                Your acceptance by clicking an acceptance button, creating an account, making payment, signing an order form, using the Platform, or continuing to use the Services constitutes valid acceptance of these Terms.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">3. Eligibility and Authority</h2>
              <p className="mb-3">
                You must be at least 18 years old and legally capable of entering into a binding contract. If you are accepting these Terms on behalf of a company, LLP, partnership, proprietor, agency, or other legal entity, you represent that you have authority to bind that entity.
              </p>
              <p>
                You may use the Platform only for lawful business purposes and in compliance with applicable laws, Meta/WhatsApp policies, telecom rules, consumer protection rules, data protection laws, and these Terms.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">4. Definitions</h2>
              <ul className="list-disc pl-5 space-y-2">
                <li><strong>Applicable Law</strong> means all applicable laws, rules, regulations, notifications, guidelines, orders, industry standards, regulatory directions, Indian laws, and applicable platform policies.</li>
                <li><strong>Client Data</strong> means all data, content, contacts, messages, templates, media, files, workflows, customer records, business data, reports, and other information submitted, uploaded, transmitted, generated, or processed by or for the Client through the Platform.</li>
                <li><strong>End User</strong> means any person or customer with whom the Client communicates using the Platform, including WhatsApp users, website visitors, leads, customers, or prospects.</li>
                <li><strong>Fees</strong> means subscription fees, setup fees, add-on fees, wallet/recharge fees, usage fees, implementation fees, integration fees, support fees, taxes, and any other amounts payable by the Client.</li>
                <li><strong>Meta/WhatsApp Policies</strong> means all applicable WhatsApp Business Terms, WhatsApp Business Messaging Policy, WhatsApp Commerce Policy, Meta Platform Terms, WhatsApp Business Platform terms, template guidelines, opt-in requirements, brand guidelines, data processing terms, and updates issued by Meta or WhatsApp.</li>
                <li><strong>Third-Party Services</strong> means services, APIs, software, payment gateways, hosting providers, Meta/WhatsApp services, analytics tools, CRMs, ecommerce platforms, cloud providers, communication networks, or integrations operated by third parties.</li>
              </ul>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">5. Account Registration and Security</h2>
              <p className="mb-3">
                You must provide true, accurate, current, and complete information during registration, onboarding, KYC, billing, and integration setup. You are responsible for maintaining confidentiality of your login credentials, API keys, tokens, OTPs, connected accounts, and authorized users.
              </p>
              <p>
                You are responsible for all activity under your account, including activity by your employees, vendors, agencies, consultants, or users whom you authorize. You must immediately notify ScaleBy at support@scaleby.in if you suspect unauthorized access, credential compromise, phishing, security breach, or misuse.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">6. License and Right to Use the Platform</h2>
              <p className="mb-3">
                Subject to payment of applicable Fees and compliance with these Terms, ScaleBy grants you a limited, revocable, non-exclusive, non-transferable, non-sublicensable right to access and use the Platform during your active subscription term for your internal business communication and automation purposes.
              </p>
              <p>
                You do not receive any ownership rights in the Platform, software, source code, APIs, documentation, design, workflows, templates, know-how, algorithms, or intellectual property of ScaleBy. All rights not expressly granted remain with ScaleBy.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">7. Services Covered</h2>
              <p className="mb-3">
                Certain features may be in beta, early access, experimental, or subject to additional terms. Beta features are provided on an as-is and as-available basis and may be modified, suspended, or discontinued at any time.
              </p>
              <ul className="list-disc pl-5 space-y-2">
                <li>WhatsApp Business API/Cloud API setup assistance, onboarding, and messaging enablement.</li>
                <li>Contact and CRM management, customer records, tags, notes, and conversation history.</li>
                <li>Messaging inbox, team assignment, message templates, media messages, quick replies, and customer support tools.</li>
                <li>Broadcast/campaign management subject to opt-in, template approval, quality limits, and applicable platform policies.</li>
                <li>Chatbot and automation flow builder, trigger-based messaging, conditions, webhooks, delay/wait nodes, variables, and integrations.</li>
                <li>Analytics, reports, usage tracking, delivery/read status where available, and performance dashboards.</li>
                <li>Integration with third-party tools such as ecommerce platforms, payment gateways, Google Sheets, CRMs, automation tools, or other business applications.</li>
                <li>Future or optional channels such as Instagram, Facebook Messenger, Google Business Messages, Telegram, or other platforms, if made available.</li>
              </ul>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">8. WhatsApp, Meta, and Third-Party Platform Compliance</h2>
              <p className="mb-3">
                You acknowledge that WhatsApp Business and Meta services are third-party services and are governed by Meta/WhatsApp policies. ScaleBy is not Meta, WhatsApp, or an affiliate of Meta.
              </p>
              <p className="mb-3">
                Your ability to use WhatsApp-related features depends on approval, availability, quality rating, phone number status, business verification, template approval, messaging limits, policy compliance, and technical availability determined by Meta/WhatsApp.
              </p>
              <p className="mb-3">
                You agree to comply with all applicable Meta/WhatsApp policies, including requirements relating to user opt-in, consent, message templates, acceptable use, prohibited content, commerce restrictions, quality ratings, user blocking/reporting, business verification, and data handling.
              </p>
              <p>
                ScaleBy may suspend, restrict, remove, or disable any message, campaign, template, workflow, integration, number, or account if we believe it violates these Terms, applicable law, Meta/WhatsApp policies, or creates risk for ScaleBy, Meta, other customers, or End Users.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">9. Client Responsibility for Opt-In, Consent, and End-User Communication</h2>
              <p className="mb-3">
                You are solely responsible for obtaining, recording, maintaining, and proving valid consent/opt-in from End Users before sending WhatsApp messages, marketing messages, promotional campaigns, automated messages, or any other communication through the Platform.
              </p>
              <p>
                You must not upload, import, buy, scrape, rent, or use unauthorized contact lists. You must provide clear information to End Users about the nature of communication they will receive, respect opt-out and deletion requests, ensure messages are lawful, and maintain sufficient proof of consent.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">10. Prohibited Use</h2>
              <p className="mb-3">You must not use the Platform for:</p>
              <ul className="list-disc pl-5 space-y-2">
                <li>Violating any law, regulation, telecom rule, data protection law, consumer protection rule, or platform policy.</li>
                <li>Sending spam, unsolicited bulk messages, deceptive messages, phishing messages, malware, scams, or fraudulent content.</li>
                <li>Promoting illegal goods or services, counterfeit products, regulated goods without proper permissions, or content restricted by Meta/WhatsApp policies.</li>
                <li>Harassing, threatening, defaming, abusing, impersonating, misleading, or harming any person or entity.</li>
                <li>Uploading viruses, malicious code, spyware, bots, scripts, or content designed to disrupt or compromise systems.</li>
                <li>Attempting to reverse engineer, copy, modify, decompile, scrape, crawl, benchmark, frame, mirror, or create competing services from the Platform.</li>
                <li>Bypassing security controls, usage limits, billing systems, authentication mechanisms, or technical restrictions.</li>
                <li>Sharing your account, API keys, tokens, or credentials with unauthorized parties.</li>
                <li>Using the Platform for high-risk, emergency, life-safety, medical emergency, or critical communication where failure could cause injury, death, or serious harm.</li>
              </ul>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">11. Fees, Wallet, Usage Charges, and Taxes</h2>
              <p className="mb-3">
                You agree to pay all applicable Fees according to the selected plan, invoice, order form, recharge, pricing page, or commercial proposal. Fees may include subscription charges, setup charges, WhatsApp conversation/message charges, wallet recharge, add-ons, integrations, implementation, support, or other usage-based charges.
              </p>
              <p className="mb-3">
                All Fees are exclusive of GST, withholding tax, payment gateway charges, bank charges, and other applicable taxes unless expressly stated otherwise. WhatsApp/Meta conversation or messaging charges may change based on Meta pricing and policies and may be passed through to you.
              </p>
              <p>
                Wallet/recharge amounts, message credits, WhatsApp credits, and usage balances are generally non-refundable and non-transferable unless expressly agreed in writing or required by law. ScaleBy may suspend or restrict Services for non-payment, insufficient wallet balance, failed payment, chargeback, suspicious transaction, or outstanding dues.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">12. Subscription, Renewal, Cancellation, and Plan Changes</h2>
              <p className="mb-3">
                Subscriptions may be monthly, annual, prepaid, postpaid, trial-based, or as otherwise specified in the order form or invoice. Unless otherwise stated, subscriptions renew automatically until cancelled according to the applicable cancellation process.
              </p>
              <p>
                Cancellation will generally take effect at the end of the current billing cycle unless otherwise agreed by ScaleBy. Plan downgrades, upgrades, add-ons, usage limits, feature access, and billing changes may apply from the next billing cycle or immediately depending on the feature and commercial terms.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">13. Trial and Free Access</h2>
              <p>
                ScaleBy may offer trials, demos, pilots, free plans, sandbox access, or limited access at its discretion. Trial or free access may have usage limits, feature restrictions, time limits, reduced support, watermarking, or other restrictions. ScaleBy may modify, withdraw, suspend, or terminate trial/free access at any time without liability.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">14. Refund Policy</h2>
              <p className="mb-3">
                Unless specifically stated in a written agreement, invoice, or applicable law, all payments made to ScaleBy are non-refundable, including subscription fees, setup fees, implementation fees, add-ons, third-party integration fees, WhatsApp/Meta usage charges, wallet recharges, message credits, and one-time service charges.
              </p>
              <p className="mb-3">
                ScaleBy may, at its sole discretion, consider a partial or full refund only in exceptional circumstances such as verified duplicate payment, verified unauthorized payment, or prolonged service failure directly attributable to ScaleBy and not caused by third-party services, Meta/WhatsApp restrictions, client configuration issues, internet/network failure, force majeure, or client misuse.
              </p>
              <p>
                Refund requests must be sent to support@scaleby.in with transaction details, invoice number, account email, and reason for the request.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">15. Client Data and Data Protection</h2>
              <p className="mb-3">
                You retain ownership of Client Data. You grant ScaleBy a limited right to host, process, transmit, store, analyze, display, and use Client Data only as necessary to provide, secure, support, improve, and operate the Platform, comply with law, enforce these Terms, and as described in our Privacy Policy.
              </p>
              <p>
                You are responsible for ensuring that Client Data is lawfully collected, uploaded, shared, and processed, and that all required notices, consents, permissions, and legal bases are obtained from End Users and other data subjects.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">16. WhatsApp Cloud API and Data Residency</h2>
              <p>
                Where the Services involve WhatsApp Business Platform or Cloud API, you acknowledge that message data, metadata, business information, and related processing may be handled by Meta/WhatsApp and may be stored, transferred, or processed in locations and data centers determined by Meta/WhatsApp. ScaleBy does not control Meta infrastructure, data residency, policy decisions, approval processes, outages, pricing, or account restrictions.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">17. Third-Party Services and Integrations</h2>
              <p className="mb-3">
                The Platform may integrate with or depend on Third-Party Services including Meta/WhatsApp, payment gateways, cloud hosting providers, CRMs, ecommerce platforms, analytics tools, automation tools, email/SMS providers, AI providers, or other APIs. Third-Party Services are governed by their own terms, privacy policies, pricing, limits, and availability.
              </p>
              <p>
                ScaleBy is not responsible for third-party outages, policy changes, rate limits, errors, data loss, suspension, pricing changes, or service discontinuation. You authorize ScaleBy to exchange data with connected Third-Party Services as necessary to provide the integration.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">18. Service Availability, Maintenance, and Support</h2>
              <p className="mb-3">
                ScaleBy will use commercially reasonable efforts to keep the Platform available. However, availability may be affected by maintenance, upgrades, infrastructure issues, third-party outages, Meta/WhatsApp limitations, internet failures, force majeure, security incidents, or other factors beyond ScaleBy reasonable control.
              </p>
              <p>
                Unless expressly agreed in writing, ScaleBy does not guarantee any specific uptime, response time, resolution time, deliverability rate, revenue outcome, lead volume, or campaign performance.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">19. Suspension and Termination</h2>
              <p>
                ScaleBy may suspend, restrict, or terminate your access immediately, with or without notice, if you breach these Terms, the Privacy Policy, payment obligations, applicable laws, Meta/WhatsApp policies, or if your use creates security, legal, operational, reputational, financial, or compliance risk.
                Upon termination, your right to use the Platform will cease. You remain responsible for all Fees, usage charges, taxes, outstanding deficits, and liabilities incurred before termination. ScaleBy may retain or delete data according to its Privacy Policy, backup policy, legal requirements, and operational retention practices.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">20. Intellectual Property Rights</h2>
              <p>
                All rights, title, and interest in the Platform, software, dashboards, APIs, workflows, templates, user interface, documentation, brand elements, logos, designs, databases, automation engine, chatbot builder, source code, trade secrets, know-how, and related intellectual property belong to ScaleBy or its licensors.
                You retain ownership of your own business content and Client Data, subject to the limited license granted to ScaleBy for operating and providing the Services.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">21. Feedback and Product Suggestions</h2>
              <p>
                If you provide feedback, suggestions, feature requests, ideas, bug reports, or recommendations, you grant ScaleBy a perpetual, worldwide, royalty-free, irrevocable right to use, modify, commercialize, and incorporate such feedback without obligation to compensate you.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">22. Confidentiality</h2>
              <p>
                Each party may receive confidential business, technical, financial, operational, customer, product, pricing, security, or other non-public information from the other party. The receiving party shall use such information only for purposes of performing under these Terms, protect it using reasonable care, and not disclose it except to authorized personnel, advisors, affiliates, contractors, service providers, or as required by law.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">23. Publicity and Use of Client Name/Logo</h2>
              <p>
                Unless you opt out in writing, you permit ScaleBy to use your business name, logo, and general description of your use of the Platform in customer lists, presentations, proposals, website, case studies, and marketing materials. ScaleBy will not publish sensitive performance metrics or confidential case studies without your approval.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">24. Disclaimers</h2>
              <p>
                The Platform and Services are provided on an as-is and as-available basis to the maximum extent permitted by law. ScaleBy disclaims all warranties, whether express, implied, statutory, or otherwise, including warranties of merchantability, fitness for a particular purpose, non-infringement, uninterrupted operation, error-free operation, message delivery, template approval, account approval, business verification, customer response, revenue increase, lead generation, campaign performance, or compatibility with all third-party systems.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">25. Limitation of Liability</h2>
              <p>
                To the maximum extent permitted by law, ScaleBy, its partners, directors, employees, contractors, affiliates, and service providers shall not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, loss of profit, loss of revenue, loss of goodwill, loss of data, business interruption, reputational harm, loss of customers, message delivery failure, account suspension by Meta/WhatsApp, or third-party service failure.
                To the maximum extent permitted by law, ScaleBy total aggregate liability arising out of or relating to these Terms or the Services shall not exceed the Fees actually paid by you to ScaleBy for the specific affected Service during the three (3) months immediately preceding the event giving rise to the claim, or INR 10,000, whichever is lower, unless a different cap is expressly agreed in writing.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">26. Indemnity</h2>
              <p>
                You agree to indemnify, defend, and hold harmless ScaleBy, its directors, employees, partners, affiliates, contractors, and service providers from and against all claims, losses, damages, penalties, fines, costs, expenses, and liabilities arising from your breach of these Terms, applicable law, Meta/WhatsApp policies, your messages, campaigns, templates, automation flows, contact lists, Client Data, End-User communications, failure to obtain consent, fraud, negligence, misuse, unauthorized access, or violation of third-party rights.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">27. Compliance with Laws</h2>
              <p>
                You must comply with all applicable local, state, national, and international laws, rules, notifications, and regulations.
                You shall comply with all applicable laws, including data protection, consumer protection, advertising, telecom, anti-spam, intellectual property, tax, export control, industry-specific, and sector-specific laws. You are responsible for determining whether the Platform is suitable for your industry and use case.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">28. Force Majeure</h2>
              <p>
                ScaleBy shall not be liable for delay, interruption, failure, or inability to perform due to events beyond its reasonable control, including acts of God, natural disasters, internet or telecom failures, cloud provider outages, Meta/WhatsApp outages or policy changes, cyberattacks, war, terrorism, riots, strikes, epidemics, pandemics, government restrictions, regulatory actions, power failures, or other force majeure events.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">29. Modifications to the Terms</h2>
              <p>
                ScaleBy may update, modify, suspend, discontinue, replace, or enhance any part of the Platform, features, APIs, integrations, pricing, usage limits, support policies, or these Terms from time to time. Updated Terms will be posted on the website, dashboard, or otherwise communicated. Your continued use of the Platform after changes become effective constitutes acceptance of the updated Terms.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">30. Governing Law, Jurisdiction, and Dispute Resolution</h2>
              <p>
                These Terms shall be governed by the laws of India. Subject to the arbitration clause below, the courts at Rajkot, Gujarat, India shall have exclusive jurisdiction, unless another jurisdiction is specified in a written agreement signed by ScaleBy.
                The parties shall first attempt to resolve disputes amicably through good-faith discussions. If a dispute is not resolved within thirty (30) days, it shall be referred to arbitration by a sole arbitrator mutually appointed by the parties under the Arbitration and Conciliation Act, 1996. The seat and venue of arbitration shall be Rajkot, Gujarat, India. The language of arbitration shall be English. The arbitral award shall be final and binding.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">31. Notices and Contact</h2>
              <p>
                All legal notices, support requests, complaints, refund requests, and account-related communications may be sent to ScaleBy Automation LLP, Brand: ScaleBy, Email: support@scaleby.in, Registered Office: 1124, RK Empire, Mavdi Chowkdi, 150ft Ring Road, Rajkot - 360004.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">32. Miscellaneous</h2>
              <p>
                You may not assign or transfer these Terms without ScaleBy prior written consent. ScaleBy may assign or transfer these Terms to an affiliate, successor, acquirer, or service provider as part of business operations, restructuring, merger, acquisition, or sale of assets.
                If any provision is held invalid or unenforceable, the remaining provisions will continue in full force. Failure to enforce any provision is not a waiver of future enforcement. These Terms, Privacy Policy, invoices, order forms, and referenced policies constitute the entire agreement between you and ScaleBy for the Services.
                Provisions relating to fees, payment, confidentiality, intellectual property, data protection, disclaimers, limitation of liability, indemnity, governing law, dispute resolution, and any clauses that by nature should survive will survive termination.
              </p>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
